### ISSUE TITLE
Download the file from Discord and put it in Assets/_Unreal_Assets/ I can't find this address, help me please 

### ISSUE THREAD

**Issue by xuxudefeng** [Suprcode/EmeraldHD#23]
2.Download the file from Discord and put it in Assets/_Unreal_Assets/ 

I'm a Unity developer and I'm interested in this project.
but I can't find this address, help me please.

**Comment by Smir** [comment]
> 2.Download the file from Discord and put it in Assets/_Unreal_Assets/
> 
> I'm a Unity developer and I'm interested in this project. but I can't find this address, help me please.

it's on LOMCN Discord, Supporting members of LOMCN can view it.

**Comment by xuxudefeng** [comment]
> > 2.Download the file from Discord and put it in Assets/_Unreal_Assets/
> > I'm a Unity developer and I'm interested in this project. but I can't find this address, help me please.
> 
> it's on LOMCN Discord, Supporting members of LOMCN can view it.

I didn't find it on LOMCN Discord, I want to participate in the development of this project, how can I become a member to support LOMCN

**Comment by xuxudefeng** [comment]
> this is done to stop people selling them off and not helping the project

I didn't find it on LOMCN Discord, I want to participate in the development of this project, how can I become a member to support LOMCN

**Comment by xuxudefeng** [comment]
> > 2.从Discord下载文件，放到Assets/_Unreal_Assets/
> > 我是一名 Unity 开发人员，我对这个项目很感兴趣。但是我找不到这个地址，请帮帮我。
> 
> 它在 LOMCN Discord 上，支持 LOMCN 的成员可以查看它。

I see, thank you

**Comment by xuxudefeng** [comment]
> 这样做是为了阻止人们卖掉它们而不是帮助项目

I see, thank you
